# Generated by Django 5.2.4 on 2025-12-30 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=50)),
                ('empjob', models.CharField(max_length=15)),
                ('empsal', models.FloatField()),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
