# Generated by Django 5.2.4 on 2026-01-06 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('cname', models.CharField(max_length=15)),
                ('custid', models.IntegerField(primary_key=True, serialize=False)),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'customer',
            },
        ),
    ]
