# Generated by Django 5.2.4 on 2026-01-09 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('empno', models.IntegerField(primary_key=True, serialize=False)),
                ('empname', models.CharField(max_length=25)),
                ('job', models.CharField(max_length=20)),
                ('salary', models.FloatField()),
            ],
            options={
                'db_table': 'emp',
            },
        ),
    ]
