# Generated by Django 5.2.4 on 2025-12-24 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmpModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empno', models.IntegerField()),
                ('empname', models.CharField(max_length=25)),
                ('empjob', models.CharField(max_length=25)),
                ('empsal', models.FloatField()),
            ],
        ),
    ]
