# Generated by Django 5.2.4 on 2025-12-15 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.IntegerField()),
                ('sname', models.CharField(max_length=20)),
                ('course', models.CharField(max_length=20)),
                ('fees', models.FloatField()),
            ],
        ),
    ]
